from django import forms
from reviews.models import Review


class ReviewForm(forms.ModelForm):
    """add review form"""
    class Meta:
        model = Review
        fields = ('product', 'review_title', 'review_body',)

    def __init__(self, *args, **kwargs):
        '''
        Add placeholders and classes, remove autogenerated
        labels and set autofocus on first field
        '''
        super().__init__(*args, **kwargs)
        placeholders = {
            'product': 'Product',
            'review_title': 'Title',
            'review_body': 'Your review',
        }


        for field in self.fields:
            placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder

        self.fields['review_title'].label = 'Title'
        self.fields['review_body'].label = 'Your review'

